translations/config.export.single.yml

Translation update for https://github.com/hechoendrupal/DrupalConsole/pull/2623

Translation update for @26233

---

translations/config.export.yml

this comes from hechoendrupal/drupalconsole@641e2bc
i'm inserting the config saving path into the «info» message

The configuration was exported at "%s"

---

translations/init.yml

translation strings for interactive `init`

init interactive

---

translations/locale.translation.status.yml

https://github.com/hechoendrupal/DrupalConsole/issues/2637

related to 

---

translations/site.new.yml

translation for https://github.com/hechoendrupal/DrupalConsole/pull/2846

related to drupalconsole#2845

---

translations/database.dump.yml

strings for https://github.com/hechoendrupal/DrupalConsole/issues/2862

added --gz option to database:dump

---

translations/database.client.yml
translations/database.query.yml

related to https://github.com/hechoendrupal/DrupalConsole/pull/2860
and https://github.com/hechoendrupal/DrupalConsole/issues/2859

strings for option «query» in database:client

---

translations/generate.breakpoint.yml
translations/generate.module.file.yml

See https://github.com/hechoendrupal/drupal-console-en/issues/47

Fixes issue 47

---

translations/config.validate.debug.yml
translations/config.validate.yml

Translation strings for drupal console PR https://github.com/hechoendrupal/DrupalConsole/pull/2993

added config validate translation strings

---

translations/site.mode.yml

strings for https://github.com/hechoendrupal/DrupalConsole/pull/2998

string for option --local in «site:mode prod»

---

translations/generate.plugin.block.yml

see https://github.com/hechoendrupal/DrupalConsole/pull/3039

generate:plugin:block missing question

---

translations/migrate.rollback.yml

**Changes**
- Add translation for migrate:rollback command

Add translation for migrate rollback command.

---

translations/generate.service.yml

I just added  a missing string in the generate.service.yml file. 
Regards.

Add missing question at generate.service.yml

---

translations/module.debug.yml

https://github.com/hechoendrupal/drupal-console-en/issues/78

[module:debug] fix issue #78

---

translations/container.debug.yml

Companion translation for new ContainerDebugCommand

[container:debug] Modified translations (new feature)

---

translations/generate.form.yml
translations/generate.service.yml

Translations modifications done

---

translations/cache.tag.invalidate.yml

Strings for hechoendrupal/drupal-console#3445.

Add cache:tag:invalidate command.

---

translations/database.restore.yml

This is on https://github.com/hechoendrupal/drupal-console/pull/3455

Better documentation for .sql.gz file support.

---

translations/application.yml

Fixed grammar when executing drush commands

Updated drush error message

---

translations/debug.theme.keys.yml

See https://github.com/hechoendrupal/drupal-console/pull/3361

Add translations for debug:theme:keys.

---

translations/generate.profile.yml

Change base-path to profile-path

[generate:profile] Update translation

---

translations/entity.delete.yml

Translation strings for hechoendrupal/drupal-console#3599 (see hechoendrupal/drupal-console#3604).

[entity:delete] Add --all option. (#3599)

---

translations/generate.ajax.command.yml

**Changes**
- Update translations to include new option for the js file

Update translations for generate ajax command.

---

translations/config.export.content.type.yml

includes string for https://github.com/hechoendrupal/drupal-console/pull/3846

added 'all' option for exporting all content types

---

translations/user.unblock.yml

This PR add a new command to allow you to unblock a user blocked.

Allow unblocking a blocked user.

---

translations/site.install.yml

This PR has the translation to the Console's PR https://github.com/hechoendrupal/drupal-console/pull/4024

[site:install] Add message to failed connection

---

translations/site.install.yml
translations/update.execute.yml

Translation to https://github.com/hechoendrupal/drupal-console/pull/4027

[update:execute] Add new keys

---

translations/generate.plugin.block.yml

This PR add strings to https://github.com/hechoendrupal/drupal-console/pull/3851

[generate:plugin:block] Rename label to plugin-label

---

translations/database.restore.yml

Added (absolute path) in file option

[database:restore] Update file string

---

translations/site.install.yml

Strings to https://github.com/hechoendrupal/drupal-console/pull/3917

Add db-url translation

---

translations/generate.site.alias.yml

String to https://github.com/hechoendrupal/drupal-console-core/pull/349

[generate:site:alias] String to drupal-console-binary

---

translations/router.rebuild.yml

String to https://github.com/hechoendrupal/drupal-console/pull/4050

[router:rebuild] String to handle unsuccessful rebuild

---

translations/module.uninstall.yml

string to https://github.com/hechoendrupal/drupal-console/pull/4062

[module:uninstall] Fix module argument

---

translations/application.yml

This PR should fix https://github.com/hechoendrupal/drupal-console/issues/2087

Update fish instructions

---

translations/config.export.single.yml
translations/config.import.yml
translations/create.nodes.yml

Strings to https://github.com/hechoendrupal/drupal-console/pull/4091

[create:nodes] Add string to revision option

---

translations/config.export.yml
translations/config.import.yml

Strings to https://github.com/hechoendrupal/drupal-console/pull/4097

[config:import | config:export] Add string to interactive mode

---

translations/generate.entity.content.yml

String to https://github.com/hechoendrupal/drupal-console/pull/4098

[generate:entity:content] Add string to owner option

---

translations/debug.update.composer.yml

Strings to https://github.com/hechoendrupal/drupal-console/pull/4105

[debug:update:composer] Add strings

---

translations/generate.theme.yml

String to https://github.com/hechoendrupal/drupal-console/pull/4111

[generate:theme] Add base theme region string

---

translations/generate.module.yml
translations/generate.plugin.block.yml
translations/multisite.new.yml

This should be fix https://github.com/hechoendrupal/drupal-console/issues/4118

Update strings to module, plugin:block, multisite:new commands

---

translations/database.add.yml

See https://github.com/hechoendrupal/drupal-console/issues/4142

Add the translation for the new --default option

---

translations/theme.install.yml

Add two translations to theme:install.
```Unable to install theme "bootstrap" due is not available```
``` Getting releases for theme "bootstrap"```
```Please select your favorite release:```

Translate messages 'getting and select release' theme:install

---

translations/common.yml
translations/generate.theme.setting.yml

messages for command generate:theme:setting

[generate:theme:setting] New command

---

translations/generate.block.type.yml

File translation on the command ```drupal generate:block:type```
**Using**
Drupal Console : 1.9.3
Drupal Console-en : 1.9.3
Drupal core : 8.7.7

[generate:block:type] New command
